# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.


# Basic Site Settings
locale                   : "en-US"
title                    : "Homepage"
title_separator          : "-"
name                     : &name "Your Name"
description              : &description "personal description"
url                      : https://sozihyun.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : sozihyun/sozihyun.github.io
site_theme               : "default"


# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "profile.jpg"
  name             : "Zixuan SU"
  pronouns         : # example: "she/her"  
  bio              : #"Short biography for the left-hand sidebar"
  location         : "Festival City, Tai Wai, HK"
  employer         : "City University of Hong Kong"
  uri              : # URL
  email            : "zixuansu4-c@my.cityu.edu.hk" 


  # Academic websites
  arxiv            : # URL - Update with the correct link to your profile
  googlescholar    : "https://scholar.google.com/citations?user=0g6zRf0AAAAJ&hl=en" 
  impactstory      : # URL
